# https://taskfile.dev

version: '3'

silent: true

dotenv: ['.env']

tasks:
  server:
    ignore_error: true
    dir: server
    cmds:
      - go run ./src
  bot:
    ignore_error: true
    dir: discord-bot
    cmds:
      - yarn install
      - yarn start
