# https://taskfile.dev

version: '3'

silent: true

dotenv: ['.env']

includes:
  go:
    taskfile: server/Taskfile.yml
    dir: server
  bot:
    taskfile: discord-bot/Taskfile.yml
    dir: discord-bot

tasks:
  server:
    ignore_error: true
    dir: server
    cmds:
      - go run ./src
  bot:
    ignore_error: true
    dir: discord-bot
    cmds:
      - yarn install
      - yarn start
  docker-deploy:
    cmds:
      - task: go:docker-deploy
      - task: bot:docker-deploy
