# https://taskfile.dev

version: '3'

silent: true

dotenv: ['.env']

includes:
  go:
    taskfile: server/Taskfile.yml
    dir: server

tasks:
  server:
    ignore_error: true
    dir: server
    cmds:
      - go run ./src
  bot:
    ignore_error: true
    dir: discord-bot
    cmds:
      - yarn install
      - yarn start
