# https://taskfile.dev

version: '3'

tasks:
  docker-build:
    cmds:
      - cp ../proto/render_server.proto .
      - cmd: docker build -t 3d-grpc-bot .
        ignore_error: true
      - rm render_server.proto
  docker-run:
    cmds:
      - docker run --rm -ti --name 3d-grpc-bot 3d-grpc-bot
  docker-stop:
    ignore_error: true
    cmds:
      - docker stop 3d-grpc-bot
  docker-deploy:
    cmds:
      - task: docker-stop
      - task: docker-build
      - task: docker-run
