// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.1
// source: src/proto/render_server.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RenderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Objects []*RenderRequest_Object `protobuf:"bytes,1,rep,name=objects,proto3" json:"objects,omitempty"`
}

func (x *RenderRequest) Reset() {
	*x = RenderRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_proto_render_server_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RenderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderRequest) ProtoMessage() {}

func (x *RenderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_render_server_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderRequest.ProtoReflect.Descriptor instead.
func (*RenderRequest) Descriptor() ([]byte, []int) {
	return file_src_proto_render_server_proto_rawDescGZIP(), []int{0}
}

func (x *RenderRequest) GetObjects() []*RenderRequest_Object {
	if x != nil {
		return x.Objects
	}
	return nil
}

type RenderReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ImageBytes []byte `protobuf:"bytes,1,opt,name=imageBytes,proto3" json:"imageBytes,omitempty"`
}

func (x *RenderReply) Reset() {
	*x = RenderReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_proto_render_server_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RenderReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderReply) ProtoMessage() {}

func (x *RenderReply) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_render_server_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderReply.ProtoReflect.Descriptor instead.
func (*RenderReply) Descriptor() ([]byte, []int) {
	return file_src_proto_render_server_proto_rawDescGZIP(), []int{1}
}

func (x *RenderReply) GetImageBytes() []byte {
	if x != nil {
		return x.ImageBytes
	}
	return nil
}

type RenderRequest_Object struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Shape  string  `protobuf:"bytes,1,opt,name=shape,proto3" json:"shape,omitempty"`
	PosX   float32 `protobuf:"fixed32,2,opt,name=posX,proto3" json:"posX,omitempty"`
	PosY   float32 `protobuf:"fixed32,3,opt,name=posY,proto3" json:"posY,omitempty"`
	PosZ   float32 `protobuf:"fixed32,4,opt,name=posZ,proto3" json:"posZ,omitempty"`
	ScaleX float32 `protobuf:"fixed32,5,opt,name=scaleX,proto3" json:"scaleX,omitempty"`
	ScaleY float32 `protobuf:"fixed32,6,opt,name=scaleY,proto3" json:"scaleY,omitempty"`
	ScaleZ float32 `protobuf:"fixed32,7,opt,name=scaleZ,proto3" json:"scaleZ,omitempty"`
}

func (x *RenderRequest_Object) Reset() {
	*x = RenderRequest_Object{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_proto_render_server_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RenderRequest_Object) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderRequest_Object) ProtoMessage() {}

func (x *RenderRequest_Object) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_render_server_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderRequest_Object.ProtoReflect.Descriptor instead.
func (*RenderRequest_Object) Descriptor() ([]byte, []int) {
	return file_src_proto_render_server_proto_rawDescGZIP(), []int{0, 0}
}

func (x *RenderRequest_Object) GetShape() string {
	if x != nil {
		return x.Shape
	}
	return ""
}

func (x *RenderRequest_Object) GetPosX() float32 {
	if x != nil {
		return x.PosX
	}
	return 0
}

func (x *RenderRequest_Object) GetPosY() float32 {
	if x != nil {
		return x.PosY
	}
	return 0
}

func (x *RenderRequest_Object) GetPosZ() float32 {
	if x != nil {
		return x.PosZ
	}
	return 0
}

func (x *RenderRequest_Object) GetScaleX() float32 {
	if x != nil {
		return x.ScaleX
	}
	return 0
}

func (x *RenderRequest_Object) GetScaleY() float32 {
	if x != nil {
		return x.ScaleY
	}
	return 0
}

func (x *RenderRequest_Object) GetScaleZ() float32 {
	if x != nil {
		return x.ScaleZ
	}
	return 0
}

var File_src_proto_render_server_proto protoreflect.FileDescriptor

var file_src_proto_render_server_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x73, 0x72, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x65, 0x6e, 0x64,
	0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0d, 0x72, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x22, 0xf3,
	0x01, 0x0a, 0x0d, 0x52, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x3d, 0x0a, 0x07, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x23, 0x2e, 0x72, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2e, 0x52, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e,
	0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x07, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x1a,
	0xa2, 0x01, 0x0a, 0x06, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x68,
	0x61, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x68, 0x61, 0x70, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x73, 0x58, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x04,
	0x70, 0x6f, 0x73, 0x58, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x73, 0x59, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x04, 0x70, 0x6f, 0x73, 0x59, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x73, 0x5a,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x04, 0x70, 0x6f, 0x73, 0x5a, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x63, 0x61, 0x6c, 0x65, 0x58, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x73, 0x63,
	0x61, 0x6c, 0x65, 0x58, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x59, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x59, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x63, 0x61, 0x6c, 0x65, 0x5a, 0x18, 0x07, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x73, 0x63,
	0x61, 0x6c, 0x65, 0x5a, 0x22, 0x2d, 0x0a, 0x0b, 0x52, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x1e, 0x0a, 0x0a, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x42, 0x79, 0x74, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x42, 0x79,
	0x74, 0x65, 0x73, 0x32, 0x57, 0x0a, 0x08, 0x52, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x65, 0x72, 0x12,
	0x4b, 0x0a, 0x0d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65, 0x6e, 0x64, 0x65, 0x72,
	0x12, 0x1c, 0x2e, 0x72, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2e, 0x52, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a,
	0x2e, 0x72, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x52,
	0x65, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x0b, 0x5a, 0x09,
	0x73, 0x72, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_src_proto_render_server_proto_rawDescOnce sync.Once
	file_src_proto_render_server_proto_rawDescData = file_src_proto_render_server_proto_rawDesc
)

func file_src_proto_render_server_proto_rawDescGZIP() []byte {
	file_src_proto_render_server_proto_rawDescOnce.Do(func() {
		file_src_proto_render_server_proto_rawDescData = protoimpl.X.CompressGZIP(file_src_proto_render_server_proto_rawDescData)
	})
	return file_src_proto_render_server_proto_rawDescData
}

var file_src_proto_render_server_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_src_proto_render_server_proto_goTypes = []interface{}{
	(*RenderRequest)(nil),        // 0: render_server.RenderRequest
	(*RenderReply)(nil),          // 1: render_server.RenderReply
	(*RenderRequest_Object)(nil), // 2: render_server.RenderRequest.Object
}
var file_src_proto_render_server_proto_depIdxs = []int32{
	2, // 0: render_server.RenderRequest.objects:type_name -> render_server.RenderRequest.Object
	0, // 1: render_server.Renderer.RequestRender:input_type -> render_server.RenderRequest
	1, // 2: render_server.Renderer.RequestRender:output_type -> render_server.RenderReply
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_src_proto_render_server_proto_init() }
func file_src_proto_render_server_proto_init() {
	if File_src_proto_render_server_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_src_proto_render_server_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RenderRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_proto_render_server_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RenderReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_proto_render_server_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RenderRequest_Object); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_src_proto_render_server_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_src_proto_render_server_proto_goTypes,
		DependencyIndexes: file_src_proto_render_server_proto_depIdxs,
		MessageInfos:      file_src_proto_render_server_proto_msgTypes,
	}.Build()
	File_src_proto_render_server_proto = out.File
	file_src_proto_render_server_proto_rawDesc = nil
	file_src_proto_render_server_proto_goTypes = nil
	file_src_proto_render_server_proto_depIdxs = nil
}
