# https://taskfile.dev

version: '3'

silent: true

tasks:
  docker-build:
    cmds:
      - echo "Building server image..."
      - docker build -t 3d-grpc-server .
  docker-run:
    cmds:
      - echo "Starting server container..."
      - docker run -tid --name 3d-grpc-server --restart unless-stopped --network=3d-grpc-net 3d-grpc-server
  docker-stop:
    ignore_error: true
    cmds:
      - echo "Stopping server container if it's running..."
      - docker stop 3d-grpc-server
      - echo "Removing server container if it exists..."
      - docker rm 3d-grpc-server
  docker-deploy:
    cmds:
      - task: docker-stop
      - task: docker-build
      - task: docker-run
  protoc:
    cmds:
      - echo "Generating pb files from proto file..."
      - protoc --go_out=. --go-grpc_out=. --proto_path ../proto render_server.proto
      - echo "Done!"
